//! Central error-code registry retained from the Python API.

pub struct ErrorCode;

impl ErrorCode {
    pub const AUTH_MISSING_CREDENTIALS: &str = "AUTH001";
    pub const AUTH_INVALID_CREDENTIALS: &str = "AUTH002";
    pub const AUTH_TOKEN_INVALID: &str = "AUTH003";
    pub const AUTH_TOKEN_MISSING: &str = "AUTH004";
    pub const AUTH_TOKEN_EXPIRED: &str = "AUTH005";
    pub const AUTH_USER_INACTIVE: &str = "AUTH007";
    pub const AUTH_UNEXPECTED_ERROR: &str = "AUTH900";
    pub const USR_ALREADY_EXISTS: &str = "USR001";
    pub const USR_NOT_FOUND: &str = "USR002";
    pub const USR_DELETE_FAILED: &str = "USR003";
    pub const USR_UPDATE_FAILED: &str = "USR004";
    pub const USR_WEAK_PASSWORD: &str = "USR005";
    pub const USR_UNAUTHORIZED_ACCESS: &str = "USR006";
    pub const USR_INVALID_OPERATION: &str = "USR007";
    pub const USR_PERMISSION_DENIED: &str = "USR008";
    pub const USR_USERNAME_INVALID: &str = "USR013";
    pub const USR_EMAIL_INVALID: &str = "USR015";
    pub const USR_TOO_MANY_ATTRIBUTES: &str = "USR016";
    pub const API_ALREADY_EXISTS: &str = "API001";
    pub const API_CREATE_FAILED: &str = "API002";
    pub const API_NOT_FOUND: &str = "API003";
    pub const API_UPDATE_NAME_FORBIDDEN: &str = "API005";
    pub const API_NO_DATA_TO_UPDATE: &str = "API006";
    pub const API_PERMISSION_DENIED: &str = "API007";
    pub const API_INVALID_REQUEST: &str = "API008";
    pub const API_PROTO_INVALID: &str = "API009";
    pub const API_PUBLIC_CREDITS_CONFLICT: &str = "API013";
    pub const END_ALREADY_EXISTS: &str = "END001";
    pub const END_CREATE_FAILED: &str = "END002";
    pub const END_NOT_FOUND: &str = "END003";
    pub const END_UPDATE_FAILED: &str = "END004";
    pub const END_DELETE_FAILED: &str = "END005";
    pub const END_INVALID_TYPE: &str = "END006";
    pub const END_VALIDATION_FAILED: &str = "END007";
    pub const END_SERVERS_REQUIRED: &str = "END008";
    pub const END_CIRCULAR_DEPENDENCY: &str = "END009";
    pub const END_PERMISSION_DENIED: &str = "END010";
    pub const END_INVALID_REQUEST: &str = "END011";
    pub const END_MISSING_PROTO: &str = "END012";
    pub const END_PATH_CONFLICT: &str = "END013";
    pub const END_METHOD_CONFLICT: &str = "END014";
    pub const END_SERVER_INVALID: &str = "END015";
    pub const END_TIMEOUT_INVALID: &str = "END016";
    pub const END_RETRIES_INVALID: &str = "END017";
    pub const END_HEADERS_INVALID: &str = "END018";
    pub const END_BODY_TRANSFORM_INVALID: &str = "END019";
    pub const END_RESPONSE_TRANSFORM_INVALID: &str = "END020";
    pub const END_LOAD_BALANCER_INVALID: &str = "END021";
    pub const END_CIRCUIT_BREAKER_INVALID: &str = "END022";
    pub const END_RATE_LIMIT_INVALID: &str = "END023";
    pub const ROLE_ALREADY_EXISTS: &str = "ROLE001";
    pub const ROLE_CREATE_FAILED: &str = "ROLE002";
    pub const ROLE_NOT_FOUND: &str = "ROLE004";
    pub const ROLE_NAME_IMMUTABLE: &str = "ROLE005";
    pub const ROLE_UPDATE_FAILED: &str = "ROLE006";
    pub const ROLE_NO_DATA_TO_UPDATE: &str = "ROLE007";
    pub const ROLE_DELETE_FAILED: &str = "ROLE008";
    pub const ROLE_PERMISSION_DENIED: &str = "ROLE009";
    pub const ROLE_INVALID_REQUEST: &str = "ROLE010";
    pub const ROLE_IN_USE: &str = "ROLE011";
    pub const ROLE_PERMISSION_INVALID: &str = "ROLE013";
    pub const ROLE_NAME_INVALID: &str = "ROLE014";
    pub const ROLE_RESERVED_NAME: &str = "ROLE015";
    pub const ROLE_DESCRIPTION_REQUIRED: &str = "ROLE016";
    pub const GRP_ALREADY_EXISTS: &str = "GRP001";
    pub const GRP_CREATE_FAILED: &str = "GRP002";
    pub const GRP_NOT_FOUND: &str = "GRP003";
    pub const GRP_UPDATE_FAILED: &str = "GRP004";
    pub const GRP_DELETE_FAILED: &str = "GRP005";
    pub const GRP_NAME_IMMUTABLE: &str = "GRP006";
    pub const GRP_NO_DATA_TO_UPDATE: &str = "GRP007";
    pub const GRP_PERMISSION_DENIED: &str = "GRP008";
    pub const GRP_INVALID_REQUEST: &str = "GRP009";
    pub const GRP_IN_USE: &str = "GRP010";
    pub const SUB_INVALID_API: &str = "SUB003";
    pub const SUB_ALREADY_EXISTS: &str = "SUB004";
    pub const SUB_NOT_FOUND: &str = "SUB005";
    pub const SUB_CREATE_FAILED: &str = "SUB006";
    pub const SUB_PERMISSION_DENIED: &str = "SUB007";
    pub const SUB_INVALID_REQUEST: &str = "SUB008";
    pub const SUB_DELETE_FAILED: &str = "SUB009";
    pub const RTG_ALREADY_EXISTS: &str = "RTG001";
    pub const RTG_CREATE_FAILED: &str = "RTG002";
    pub const RTG_NOT_FOUND: &str = "RTG004";
    pub const RTG_UPDATE_FAILED: &str = "RTG005";
    pub const RTG_DELETE_FAILED: &str = "RTG006";
    pub const RTG_NO_DATA_TO_UPDATE: &str = "RTG007";
    pub const RTG_NAME_IMMUTABLE: &str = "RTG008";
    pub const RTG_PERMISSION_DENIED: &str = "RTG009";
    pub const RTG_INVALID_REQUEST: &str = "RTG010";
    pub const RTG_PRIORITY_CONFLICT: &str = "RTG011";
    pub const RTG_PATH_INVALID: &str = "RTG012";
    pub const RTG_CONDITION_INVALID: &str = "RTG013";
    pub const CRD_GROUP_EXISTS: &str = "CRD001";
    pub const CRD_CREATE_FAILED: &str = "CRD002";
    pub const CRD_GROUP_IMMUTABLE: &str = "CRD003";
    pub const CRD_NOT_FOUND: &str = "CRD004";
    pub const CRD_UPDATE_FAILED: &str = "CRD005";
    pub const CRD_NO_DATA_TO_UPDATE: &str = "CRD006";
    pub const CRD_DELETE_NOT_FOUND: &str = "CRD007";
    pub const CRD_DELETE_FAILED: &str = "CRD008";
    pub const CRD_GROUP_NAME_REQUIRED: &str = "CRD009";
    pub const CRD_API_KEY_REQUIRED: &str = "CRD010";
    pub const CRD_DATABASE_ERROR: &str = "CRD011";
    pub const CRD_DATABASE_ERROR_UPDATE: &str = "CRD012";
    pub const CRD_DATABASE_ERROR_DELETE: &str = "CRD013";
    pub const CRD_USERNAME_MISMATCH: &str = "CRD014";
    pub const CRD_USER_CREDITS_ERROR: &str = "CRD015";
    pub const CRD_GET_ALL_ERROR: &str = "CRD016";
    pub const CRD_USER_NOT_FOUND: &str = "CRD017";
    pub const CRD_GET_USER_ERROR: &str = "CRD018";
    pub const CRD_LIST_ERROR: &str = "CRD020";
    pub const CRD_FETCH_ERROR: &str = "CRD021";
    pub const CRD_RETRIEVE_ERROR: &str = "CRD022";
    pub const GTW_UPSTREAM_ERROR: &str = "GTW001";
    pub const GTW_TIMEOUT: &str = "GTW002";
    pub const GTW_NO_AVAILABLE_SERVERS: &str = "GTW003";
    pub const GTW_INVALID_REQUEST: &str = "GTW004";
    pub const GTW_RATE_LIMIT_EXCEEDED: &str = "GTW005";
    pub const GTW_SERVICE_UNAVAILABLE: &str = "GTW006";
    pub const GTW_AUTHENTICATION_REQUIRED: &str = "GTW007";
    pub const GTW_SUBSCRIPTION_REQUIRED: &str = "GTW008";
    pub const GTW_CIRCUIT_BREAKER_OPEN: &str = "GTW010";
    pub const GTW_INVALID_ENDPOINT: &str = "GTW011";
    pub const GTW_PROTO_DECODE_ERROR: &str = "GTW013";
    pub const GTW_UNEXPECTED_ERROR: &str = "GTW999";
    pub const CFG_PERMISSION_DENIED: &str = "CFG001";
    pub const CFG_API_PERMISSION_DENIED: &str = "CFG002";
    pub const CFG_ENDPOINT_PERMISSION_DENIED: &str = "CFG003";
    pub const CFG_GROUP_PERMISSION_DENIED: &str = "CFG004";
    pub const CFG_ROLE_PERMISSION_DENIED: &str = "CFG005";
    pub const CFG_ROUTING_PERMISSION_DENIED: &str = "CFG006";
    pub const CFG_SUBSCRIPTION_PERMISSION_DENIED: &str = "CFG007";
    pub const CFG_NOT_FOUND: &str = "CFG404";
    pub const SEC_PERMISSION_DENIED: &str = "SEC001";
    pub const SEC_UPDATE_FAILED: &str = "SEC002";
    pub const SEC_INVALID_IP: &str = "SEC003";
    pub const SEC_INVALID_SETTING: &str = "SEC004";
    pub const SEC_PROTECTED_SETTING: &str = "SEC005";
    pub const LOG_PERMISSION_DENIED: &str = "LOG001";
    pub const LOG_INVALID_LEVEL: &str = "LOG002";
    pub const LOG_UPDATE_FAILED: &str = "LOG003";
    pub const LOG_QUERY_FAILED: &str = "LOG004";
    pub const LOG_EXPORT_FAILED: &str = "LOG005";
    pub const MON_PERMISSION_DENIED: &str = "MON001";
    pub const MON_QUERY_FAILED: &str = "MON002";
    pub const MON_UNEXPECTED_ERROR: &str = "MON003";
    pub const MEM_PERMISSION_DENIED: &str = "MEM001";
    pub const MEM_DUMP_FAILED: &str = "MEM002";
    pub const MEM_OPERATION_FAILED: &str = "MEM003";
    pub const DEMO_ALREADY_SEEDED: &str = "DEMO001";
    pub const DEMO_SEED_FAILED: &str = "DEMO999";
    pub const TLS_PERMISSION_DENIED: &str = "TLS001";
    pub const TLS_UNEXPECTED_ERROR: &str = "TLS999";
    pub const GEN_INVALID_REQUEST: &str = "GEN001";
    pub const GEN_VALIDATION_ERROR: &str = "GEN002";
    pub const ISE_INTERNAL_ERROR: &str = "ISE001";
    pub const REQ_BODY_TOO_LARGE: &str = "REQ001";
    pub const VAL_INVALID_JSON: &str = "VAL001";
    pub const JWT_DECODE_ERROR: &str = "JWT001";
    pub const RATE_LIMIT_EXCEEDED: &str = "RATE_LIMIT_EXCEEDED";
}

pub type ErrorCodes = ErrorCode;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preserves_representative_python_error_code_values() {
        assert_eq!(ErrorCode::AUTH_MISSING_CREDENTIALS, "AUTH001");
        assert_eq!(ErrorCode::END_RATE_LIMIT_INVALID, "END023");
        assert_eq!(ErrorCode::CRD_RETRIEVE_ERROR, "CRD022");
        assert_eq!(ErrorCodes::GTW_UNEXPECTED_ERROR, "GTW999");
        assert_eq!(ErrorCode::RATE_LIMIT_EXCEEDED, "RATE_LIMIT_EXCEEDED");
    }
}
